;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname blackjack) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ())))
;;
;;*************************************************************
;;Rihao Kang (20560708)
;;CS 135 Fall 2014
;;Assignment 02, problem 3 (blackjack)
;;*************************************************************
;; Q3
;; Produce appropiate symbols or actions to help blackjack player to
;; choose a wise decision.
;; blackjack-hard Nat Nat -> Sym
;; Requires: 5 <= player-score <=20
;;           1 <= dealer's card <= 10
;; examples:

(check-expect (blackjack-hard 15 4) 'stay)
(check-expect (blackjack-hard 16 8) 'hit)
(check-expect (blackjack-hard 15 10) 'surrender)
(check-expect (blackjack-hard 9 5) 'double)

(define (blackjack-hard player-score dealer-card)
  (cond [(>= player-score 17) 'stay]
        
        [(and (and (<= player-score 16) 
                   (>= player-score 13)) 
              (and (<= dealer-card 6) 
                   (> dealer-card 1))) 'stay]
        
        [(and (= player-score 16) 
              (and (>= dealer-card 7) 
                   (<= dealer-card 8))) 'hit]
        
        [(and (= player-score 16) 
         (or (= dealer-card 9) 
              (= dealer-card 10))) 'surrender]
        
        [(and (= player-score 16) 
              (= dealer-card 1)) 'surrender]
        
        [(and (= player-score 15)
          (or (= dealer-card 7)
                  (= dealer-card 8)
                  (= dealer-card 9) 
                  (= dealer-card 1))) 
               'hit]
        
        [(and (= player-score 15) 
              (= dealer-card 10)) 'surrender]
        
        [(and (and (>= player-score 12)
                   (<= player-score 14)) 
              (or (= dealer-card 7)
                  (= dealer-card 8)
                  (= dealer-card 9)
                   (= dealer-card 10)
                   (= dealer-card 1))) 'hit]
        
        [(and (= player-score 12) 
              (or (= dealer-card 2)
                   (= dealer-card 3))) 'hit]
        
        [(and (= player-score 12) 
              (and (>= dealer-card 4)
                   (<= dealer-card 6))) 'stay]
        
        [(or (and (or (= player-score 11)
                   (= player-score 10))
              (or (= dealer-card 2)
                  (= dealer-card 3)
                  (= dealer-card 4)
                  (= dealer-card 5)
                  (= dealer-card 6)
                  (= dealer-card 7)
                  (= dealer-card 8)
                  (= dealer-card 9)))
             (and (= player-score 11)
                  (= dealer-card 10))
             (and (= player-score 9)
                  (and (>= dealer-card 3)
                  (<= dealer-card 6)))) 'double]
        
        [(or (and (= player-score 11) (= dealer-card 1))
             (and (= player-score 10) (or (= dealer-card 10) (= dealer-card 1)))
             (and (= player-score 9) (= dealer-card 2))
             (and (= player-score 9) (or (>= dealer-card 7) (<= dealer-card 10) ))
             (and (>= player-score 5) (<= player-score 8))) 'hit]))


;;tests:


(check-expect (blackjack-hard 20 1) 'stay)
(check-expect (blackjack-hard 20 2) 'stay)
(check-expect (blackjack-hard 20 3) 'stay)
(check-expect (blackjack-hard 20 4) 'stay)
(check-expect (blackjack-hard 20 5) 'stay)
(check-expect (blackjack-hard 20 6) 'stay)
(check-expect (blackjack-hard 20 7) 'stay)
(check-expect (blackjack-hard 20 8) 'stay)
(check-expect (blackjack-hard 20 9) 'stay)
(check-expect (blackjack-hard 20 10) 'stay)
(check-expect (blackjack-hard 19 1) 'stay)
(check-expect (blackjack-hard 19 2) 'stay)
(check-expect (blackjack-hard 19 3) 'stay)
(check-expect (blackjack-hard 19 4) 'stay)
(check-expect (blackjack-hard 19 5) 'stay)
(check-expect (blackjack-hard 19 6) 'stay)
(check-expect (blackjack-hard 19 7) 'stay)
(check-expect (blackjack-hard 19 8) 'stay)
(check-expect (blackjack-hard 19 9) 'stay)
(check-expect (blackjack-hard 19 10) 'stay)
(check-expect (blackjack-hard 18 1) 'stay)
(check-expect (blackjack-hard 18 2) 'stay)
(check-expect (blackjack-hard 18 3) 'stay)
(check-expect (blackjack-hard 18 4) 'stay)
(check-expect (blackjack-hard 18 5) 'stay)
(check-expect (blackjack-hard 18 6) 'stay)
(check-expect (blackjack-hard 18 7) 'stay)
(check-expect (blackjack-hard 18 8) 'stay)
(check-expect (blackjack-hard 18 9) 'stay)
(check-expect (blackjack-hard 18 10) 'stay)
(check-expect (blackjack-hard 17 1) 'stay)
(check-expect (blackjack-hard 17 2) 'stay)
(check-expect (blackjack-hard 17 3) 'stay)
(check-expect (blackjack-hard 17 4) 'stay)
(check-expect (blackjack-hard 17 5) 'stay)
(check-expect (blackjack-hard 17 6) 'stay)
(check-expect (blackjack-hard 17 7) 'stay)
(check-expect (blackjack-hard 17 8) 'stay)
(check-expect (blackjack-hard 17 9) 'stay)
(check-expect (blackjack-hard 17 10) 'stay)
(check-expect (blackjack-hard 16 2) 'stay)
(check-expect (blackjack-hard 16 3) 'stay)
(check-expect (blackjack-hard 16 4) 'stay)
(check-expect (blackjack-hard 16 5) 'stay)
(check-expect (blackjack-hard 16 6) 'stay)
(check-expect (blackjack-hard 16 7) 'hit)
(check-expect (blackjack-hard 16 8) 'hit)
(check-expect (blackjack-hard 16 9) 'surrender)
(check-expect (blackjack-hard 16 10) 'surrender)
(check-expect (blackjack-hard 16 1) 'surrender)
(check-expect (blackjack-hard 15 2) 'stay)
(check-expect (blackjack-hard 15 3) 'stay)
(check-expect (blackjack-hard 15 4) 'stay)
(check-expect (blackjack-hard 15 5) 'stay)
(check-expect (blackjack-hard 15 6) 'stay)
(check-expect (blackjack-hard 15 1) 'hit)
(check-expect (blackjack-hard 15 7) 'hit)
(check-expect (blackjack-hard 15 8) 'hit)
(check-expect (blackjack-hard 15 9) 'hit)
(check-expect (blackjack-hard 15 10) 'surrender)
(check-expect (blackjack-hard 14 1) 'hit)
(check-expect (blackjack-hard 14 2) 'stay)
(check-expect (blackjack-hard 14 3) 'stay)
(check-expect (blackjack-hard 14 4) 'stay)
(check-expect (blackjack-hard 14 5) 'stay)
(check-expect (blackjack-hard 14 6) 'stay)
(check-expect (blackjack-hard 14 7) 'hit)
(check-expect (blackjack-hard 14 8) 'hit)
(check-expect (blackjack-hard 14 9) 'hit)
(check-expect (blackjack-hard 14 10) 'hit)
(check-expect (blackjack-hard 13 1) 'hit)
(check-expect (blackjack-hard 13 2) 'stay)
(check-expect (blackjack-hard 13 3) 'stay)
(check-expect (blackjack-hard 13 4) 'stay)
(check-expect (blackjack-hard 13 5) 'stay)
(check-expect (blackjack-hard 13 6) 'stay)
(check-expect (blackjack-hard 13 7) 'hit)
(check-expect (blackjack-hard 13 8) 'hit)
(check-expect (blackjack-hard 13 9) 'hit)
(check-expect (blackjack-hard 13 10) 'hit)
(check-expect (blackjack-hard 12 1) 'hit)
(check-expect (blackjack-hard 12 2) 'hit)
(check-expect (blackjack-hard 12 3) 'hit)
(check-expect (blackjack-hard 12 4) 'stay)
(check-expect (blackjack-hard 12 5) 'stay)
(check-expect (blackjack-hard 12 6) 'stay)
(check-expect (blackjack-hard 12 7) 'hit)
(check-expect (blackjack-hard 12 8) 'hit)
(check-expect (blackjack-hard 12 9) 'hit)
(check-expect (blackjack-hard 12 10) 'hit)
(check-expect (blackjack-hard 11 1) 'hit)
(check-expect (blackjack-hard 11 2) 'double)
(check-expect (blackjack-hard 11 3) 'double)
(check-expect (blackjack-hard 11 4) 'double)
(check-expect (blackjack-hard 11 5) 'double)
(check-expect (blackjack-hard 11 6) 'double)
(check-expect (blackjack-hard 11 7) 'double)
(check-expect (blackjack-hard 11 8) 'double)
(check-expect (blackjack-hard 11 9) 'double)
(check-expect (blackjack-hard 11 10) 'double)
(check-expect (blackjack-hard 10 1) 'hit)
(check-expect (blackjack-hard 10 2) 'double)
(check-expect (blackjack-hard 10 3) 'double)
(check-expect (blackjack-hard 10 4) 'double)
(check-expect (blackjack-hard 10 5) 'double)
(check-expect (blackjack-hard 10 6) 'double)
(check-expect (blackjack-hard 10 7) 'double)
(check-expect (blackjack-hard 10 8) 'double)
(check-expect (blackjack-hard 10 9) 'double)
(check-expect (blackjack-hard 10 10) 'hit)
(check-expect (blackjack-hard 9 1) 'hit)
(check-expect (blackjack-hard 9 2) 'hit)
(check-expect (blackjack-hard 9 3) 'double)
(check-expect (blackjack-hard 9 4) 'double)
(check-expect (blackjack-hard 9 5) 'double)
(check-expect (blackjack-hard 9 6) 'double)
(check-expect (blackjack-hard 9 7) 'hit)
(check-expect (blackjack-hard 9 8) 'hit)
(check-expect (blackjack-hard 9 9) 'hit)
(check-expect (blackjack-hard 9 10) 'hit)
(check-expect (blackjack-hard 8 1) 'hit)
(check-expect (blackjack-hard 8 2) 'hit)
(check-expect (blackjack-hard 8 3) 'hit)
(check-expect (blackjack-hard 8 4) 'hit)
(check-expect (blackjack-hard 8 5) 'hit)
(check-expect (blackjack-hard 8 6) 'hit)
(check-expect (blackjack-hard 8 7) 'hit)
(check-expect (blackjack-hard 8 8) 'hit)
(check-expect (blackjack-hard 8 9) 'hit)
(check-expect (blackjack-hard 8 10) 'hit)
(check-expect (blackjack-hard 7 1) 'hit)
(check-expect (blackjack-hard 7 2) 'hit)
(check-expect (blackjack-hard 7 3) 'hit)
(check-expect (blackjack-hard 7 4) 'hit)
(check-expect (blackjack-hard 7 5) 'hit)
(check-expect (blackjack-hard 7 6) 'hit)
(check-expect (blackjack-hard 7 7) 'hit)
(check-expect (blackjack-hard 7 8) 'hit)
(check-expect (blackjack-hard 7 9) 'hit)
(check-expect (blackjack-hard 7 10) 'hit)
(check-expect (blackjack-hard 6 1) 'hit)
(check-expect (blackjack-hard 6 2) 'hit)
(check-expect (blackjack-hard 6 3) 'hit)
(check-expect (blackjack-hard 6 4) 'hit)
(check-expect (blackjack-hard 6 5) 'hit)
(check-expect (blackjack-hard 6 6) 'hit)
(check-expect (blackjack-hard 6 7) 'hit)
(check-expect (blackjack-hard 6 8) 'hit)
(check-expect (blackjack-hard 6 9) 'hit)
(check-expect (blackjack-hard 6 10) 'hit)
(check-expect (blackjack-hard 5 1) 'hit)
(check-expect (blackjack-hard 5 2) 'hit)
(check-expect (blackjack-hard 5 3) 'hit)
(check-expect (blackjack-hard 5 4) 'hit)
(check-expect (blackjack-hard 5 5) 'hit)
(check-expect (blackjack-hard 5 6) 'hit)
(check-expect (blackjack-hard 5 7) 'hit)
(check-expect (blackjack-hard 5 8) 'hit)
(check-expect (blackjack-hard 5 9) 'hit)
(check-expect (blackjack-hard 5 10) 'hit)




  